version: '3.3'
services:
  lsyncd:
    image: davinbao/lsyncd:latest
    deploy:
      replicas: 1
      endpoint_mode: vip
      placement:
        constraints:
          - node.labels.node == 208
      resources:
        limits:
          memory: 512M
    volumes:
    - /xmisp/docker/lsyncd/conf/lsyncd.conf:/etc/lsyncd.conf
    - /xmisp/docker/bind/conf:/data
    - /root/.ssh:/root/.ssh:ro